### ISSUE TITLE
Unit frames blizz like health options

### ISSUE THREAD

**Issue by Ser-Geeves** [kkthnx-wow/KkthnxUI_Classic#63]
Hey, I am trying to configure the target health frames to show accurate health numbers, % + current/max health like in the blizzard settings. But I can not seem to find the right option to make it work in KkthnxUI. The best I can get to is % health. 

Is this a feature already in the mod, and if so, where ? 
If not can you make it so it detects Blizzard settings and copies that instead?

**Comment by Ser-Geeves** [comment]
![image](https://user-images.githubusercontent.com/7427719/70317927-0f6bd780-181f-11ea-844a-ee9fe88c0c0d.png)

Image for clarification, as you can see the hunter has 100 (%) hitpoints, yet I can see the accurate mana. When I target myself, I get accurate health numbers. Target anything else, NPC's Hostile/Friendly players, Hostile/Neutral mobs I can only see % health.

**Comment by Baine** [comment]
seeing the actual amount of HP/MP is actually not possible without using
additional addons (in this case, RealMobHealth)

or short: it's not a bug, it's a feature (blizzard wants it that way, since
it was that way in vanilla too)

Am Fr., 6. Dez. 2019 um 11:55 Uhr schrieb Geeves <notifications@github.com>:

**Comment by Ser-Geeves** [comment]
So.. without unit frames I can see a thing, but with unit frames I can not?

**Comment by Baine** [comment]
as i said, that is not possible in WoW Classic
blizz ui, targetting myself
![grafik](https://user-images.githubusercontent.com/6566469/70698026-ee93fe00-1cc6-11ea-826f-222b00408b24.png)

blizz ui, targetting an npc:
![grafik](https://user-images.githubusercontent.com/6566469/70698066-02d7fb00-1cc7-11ea-88bb-566ea8315686.png)

so no, it's not visible by the blizz ui either
(please don't confuse classic and retail WoW regarding this, since HP/MP are perfectly visible/accessible in retail)
